spring.application.name=api-gateway
server.port=8080

services.auth.url=${AUTH_SERVICE_URL:http://localhost:8081}
services.wallet.url=${WALLET_SERVICE_URL:http://localhost:8082}
services.order.url=${ORDER_SERVICE_URL:http://localhost:8083}
services.portfolio.url=${PORTFOLIO_SERVICE_URL:http://localhost:8084}

broker.platform-id=550e8400-e29b-41d4-a716-446655440999

jwt.secret=${JWT_SECRET:mysupersecretkeymysupersecretkeymysupersecretkey123456}

internal.api-key=${INTERNAL_API_KEY:secret123}


