spring.application.name=api-gateway
server.port=8080

services.auth.url=http://localhost:8081
services.wallet.url=http://localhost:8082
services.order.url=http://localhost:8083
services.portfolio.url=http://localhost:8084

broker.platform-id=550e8400-e29b-41d4-a716-446655440999

jwt.secret=mysupersecretkeymysupersecretkeymysupersecretkey123456


