spring.application.name=api-gateway
server.port=9000

services.auth.url=http://localhost:9001
services.wallet.url=http://localhost:9002
services.order.url=http://localhost:9003
services.portfolio.url=http://localhost:9004
services.fee.url=http://localhost:9005
services.notification.url=${SERVICES_NOTIFICATION_URL:http://localhost:9006}

broker.platform-id=550e8400-e29b-41d4-a716-446655440999

jwt.secret=${JWT_SECRET:mysupersecretkeymysupersecretkeymysupersecretkey123456}

internal.api-key=${INTERNAL_API_KEY:secret123}
cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:[*],http://127.0.0.1:[*],http://192.168.*.*:[*],http://10.*.*.*:[*],http://172.*.*.*:[*]}

